package fund;

public enum Phrase {

    PENSION_FUNDS,
    STAT_PAGE_OPTION,
    STAT_DESCRIPTION,
    WORKERS_PENSION,
    STATE_PENSION,
    MEDIAN_PENSION_OF_FUNDS,
    AVERAGE_PENSION_WORKER,
    TRY_AGAIN,
    CONTINUE_OPTION,
    ATTENTION,
    BYE,
    SUCCESS_INFO,
    FILE_NOT_FOUND,
    POPULAR_FUND,
    HIGHEST_PENSION,
    HIGHEST_STATE_PENSION,
    LOSERS,
    HIGHEST_PENSION_AGE,
    INPUT_AGE,
    WORKER_HIGHEST_PENSION_AGE,
    YOUNGEST_WORKER_STATE_FUND,
    AVERAGE_PENSION_FUNDS
    }
