package fund;

public enum Request {
    MOST_POPULAR_FUND,
    WORKER_WITH_BIGGEST_PENSION,
    LOSERS,
    AVERAGE_PENSION_OF_FUNDS,
    AVERAGE_PENSION_OF_WORKERS,
    BIGGEST_PENSION_DEPENDS_ON_AGE,
    YOUNGEST_WORKER_OF_STATE_FUNDS


}
